### ISSUE TITLE
Descrição dos jogos

### ISSUE THREAD

**Issue by juniorpires** [Wylianne/Meduca#1]
@Wylianne  tu poderia fazer uma breve descrição dos jogos e o que falta implementar? Porque aí eu e Victor  @VictorCardoso22 poderíamos já começar a desenvolver algo. 
Valeu

**Comment by Wylianne** [comment]
# **Soma Ossos**

O Quebra Ossos é um jogo de fases, quando o jogador seleciona esse jogo uma tela com as fazes bloqueadas e desbloqueadas aparece, o jogador só desbloqueia a fase seguinte quando finaliza a fase atual. Este jogo é bem parecido com o jogo da somar onde aparecem espaços em branco e uma sentença. 

Ex.: _____ + _____ = 8

No caso acima ele pede dois números  que somados o seu resultado seja 8, podendo ser 1 + 7, 2 + 6, 3 + 4... e assim por diante.
Nesse jogo será solicitado os ossos que compõem uma determinada parte do corpo, por exemplo, o jogo solicita os ossos que compõem a perna, ela possui dois ossos, a tíbia e a fíbula, na tela do jogo aparecerá vários ossos e o jogador terá que selecionar esses dois, quando o osso é selecionado ele desaparece da parte onde aparecem as possibilidades e aparece na sentença.
O jogo também pode contar com um sistema de tempo, onde após determinado período ele automaticamente perde o jogo.
Se possível quando o osso desaparecer das possibilidades um outro ossos aparece automaticamente. Os ossos que aparecem na parte de possibilidades são aleatórios, dessa forma o jogador pode solicitar no máximo três vezes que as possibilidades sejam refeitas.
Um sistema de tempo também seria interessante, pois auxiliaria para efetuar o calculo dos pontos com base no tempo, já que o jogador só poderá passar para a fase seguinte se responder a atual.


# **Palavras Cruzadas**

Jogo comum de palavras cruzadas, ficando a cargo de quem implementar colocar inputs em cada letra ou um input que verifica se a palavra digitada corresponde a palavra da lacuna e se corresponder preencher as lacunas automaticamente.

# **Quebra Ossos**

O jogo Quebra Ossos é basicamente o jogo da forca, onde o jogador deverá adivinhar letra por letra que corresponde a palavra, preenchendo assim as lacunas, e que satisfazem as dicas dadas. No jogo original, a cada letra errada que o jogador escolhe um boneco de linhas é desenhado na forca e o jogador perde se todo o boneco for desenhado, por ser um jogo voltado para área de saúde ao invés de um boneco de linhas foi escolhido um esqueleto, onde a cada letra errada ossos do esqueleto são quebrados e o jogador perderá quando não houver mais ossos para quebrar, além disso, o jogo possui uma pontuação que servirá para alimentar as estatísticas, cada jogo possui uma pontuação inicial de 100 e a cada erro ou pedido de dica a pontuação diminui. 
As dicas aparecem ao tocar nos corações, cada coração possui uma dica e quando tocado ele se quebra e exibe a dica. A primeira dica pode ser exibida sem perca na pontuação, mas se o jogador não exibí-la ela será mostrada automaticamente após a segunda letra errada. Nas duas dicas seguintes a pontuação do jogador é decrementada e se o jogador decidir não exibí-las elas serão exibidas automaticamente após 4 e 5 erros de letras respectivamente. O jogador só poderá errar seis letras ao total.

# **Quiz**

O jogo de Quiz é um jogo de perguntas e respostas comum a tantos outros, tendo somente uma diferença, ao invés do jogador selecionar quantas perguntas quer responder ele começará a responder  as perguntas e irá finalizar quando quiser. Os botões de próxima pergunta e finalizar o jogo só aparecem após selecionar uma resposta, somente é possível selecionar uma única resposta correta.
Como todos os outros jogos este também conta com sistema de pontuação, ao finalizar a partida é calculada uma porcentagem de acertos e erros para alimentar banco de estatísticas.

# **Tiro ao alvo**

Uma máquina que gera ossos aleatórios e "objetos" que somam tempo, onde eles são soltos em uma esteira e são levados ao final da tela... O jogador terá que tocar em determinados ossos, por exemplo no topo da tela aparecerá o nome de um ossos e ele terá que tocar em todos os ossos que correspondem ao ossos referente ao nome, se errar o jogo. O jogo também terá um contador se ele chegar a zero o jogador perde ele também pode aumentar seu tempo se clicar no "objeto" de tempo ao passar o tempo do jogo a velocidade que os ossos são levados vai aumentando gradativamente.
